export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Why } from './why/Why'
export { default as Services } from './services/Services'
export { default as Offers } from './offers/Offers'
export { default as Testimonials } from './testimonials/Testimonials'
export { default as FAQ } from './faq/FAQ'
export { default as CTA } from './cta/CTA'
